name: Unity - Activation

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Activation File
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.17f1
