name: Generate Unity License
on:
  workflow_dispatch:

jobs:
  request-license:
    runs-on: ubuntu-latest
    steps:
      - name: Request Unity License
        uses: game-ci/unity-request-activation-file@v2
