name: Generate Unity License
on:
  workflow_dispatch:

jobs:
  request-license:
    runs-on: ubuntu-latest
    steps:
      - name: Request Unity License
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.17f1

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: unity-license
          path: Unity_v2022.3.17f1.alf
